services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: next_event_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - next-event_postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: next_event_backend
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm start"

  # Serviço do Front-end 
  frontend:
    container_name: next_event_frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - backend

volumes:
  next-event_postgres-data: